mod 'puppet-kibana', '8.0.0'
mod 'puppet-elastic_stack', '9.0.0'
mod 'puppetlabs-stdlib', '9.4.1'
mod 'puppetlabs-apt', '9.1.0'
mod 'puppet-yum', '7.1.0'
mod 'puppetlabs-stdlib', '9.4.1'
mod 'puppetlabs-concat', '9.0.0'
mod 'puppet-logstash', '7.0.0'
mod 'puppet-elasticsearch', '8.1.0'
mod 'puppet-elastic_stack', '9.0.0'
mod 'puppetlabs-java', '10.1.2'
mod 'puppet-archive', '7.1.0'
mod 'puppetlabs-java_ks', '5.0.0'

